### ISSUE TITLE
CPS1.5: 3rd player controller not recognized.

### ISSUE THREAD

**Issue by SumolX** [jotego/jtbin#148]
In the main menu I can assign the inputs and reassign per game.  However, both  test mode and in game none of the buttons are being recognized.  This applies to all 3 and 4 player games.

**Comment by jotego** [comment]
Excuse me, but I cannot which game are you referring to?

**Comment by SumolX** [comment]
I tried C&D and warriors of fate.

**Comment by Epyc7** [comment]
I can confirm this also.  Configured Player 3/4 controls but cannot insert coin for Player 3/4 in Cadillacs and Dinosaurs. I assume this is the same for other 3/4 player games as well.

However, Final Fight Anniversary Edition 3 Player works as expected.

**Comment by jotego** [comment]
Update: the memory map seems ok. Button mapping too. The culprit is still unclear.

**Comment by uncon** [comment]
I can confirm the same behavior. I have been unsuccessful in getting >2 simultaneous player inputs working for CPS games.

**Comment by jotego** [comment]
I think it is a specific problem of CPS1.5. The 3-player games in CPS1 should be ok.

**Comment by uncon** [comment]
I just confirmed that, indeed, CPS 1 seems alright, and only the CPS 1.5 games I've tested exhibit this issue.

**Comment by jotego** [comment]
Technical notes:
The CPU does access the 3rd player inputs in simulation. I can see joy3_cs going high.

**Comment by manast** [comment]
In Cadillac & Dinosaurs I noticed that you can insert coins for player 3 with the "9" key instead of "7" that would have been the correct mapping. Unfortunatelly I could not find the key for start so I could not test the other buttons. Maybe it is just a matter of wrong mapping?

**Comment by manast** [comment]
forget my previous comment, "9" seems to mean "insert coin for all players"... 
But I can confirm that on Knights of the round all three players work perfectly.

**Comment by jotego** [comment]
Fixed in https://github.com/jotego/jtcps1/commit/63db0d01d1ce665856c5e88e9b2e7feec5a214d5
Thanks to blackwine for the edit.
I will update the binaries shortly.

**Comment by trukjr** [comment]
C&D still does not work with 3 players after the Update_All script was run for the MiSTer.

**Comment by jotego** [comment]
Please try updating again, maybe something went wrong. I have checked it here and I can control the third player correctly. 
Could this be related to your setup?

**Comment by trukjr** [comment]
> Please try updating again, maybe something went wrong. I have checked it here and I can control the third player correctly.
> Could this be related to your setup?

Hey Jotego,

I ran the Update_All script last night and both the CPS1 and CPS15 files updated correctly during the Jotego section.  Afterwards,  C&D worked perfectly with 3 players!  I'm not sure if there were any changes made since I ran this on Monday.  Thanks!
